export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
export const GITHUB_LOGIN = 'GITHUB_LOGIN';
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const PASSWORD_LOGIN = "PASSWORD_LOGIN";
export const USER_LOGOUT = 'USER_LOGOUT'

